{
 "title": "Kafka Connect",
 "tags": [
  "kafka",
  "connect"
 ],
 "refresh": "30s",
 "panels": [
  {
   "title": "Worker Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(up{job=\"kafka_connect\"} == 1)"
    }
   ]
  },
  {
   "title": "Connector Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_count or vector(0)"
    }
   ]
  },
  {
   "title": "Running Connectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "(kafka_connect_worker_connector_count - kafka_connect_worker_connector_startup_failure) or vector(0)"
    }
   ]
  },
  {
   "title": "Failed Connectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_startup_failure or vector(0)"
    }
   ]
  },
  {
   "title": "Task Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "kafka_connect_worker_task_count or vector(0)"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "kafka_connect_worker_task_startup_failure or vector(0)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(hostname) (irate(node_cpu_seconds_total{mode=\"idle\", role=\"connect\"}[5m])) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{role=\"connect\"} / node_memory_MemTotal_bytes{role=\"connect\"})) * 100",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}